api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            jwt:
                name: Authorization
                type: header
    http_cache:
        invalidation:
            enabled: false
            
        public: true
    defaults:
        cache_headers:
            max_age: 1800
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']



